# Generated by Django 5.0.6 on 2024-07-17 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoapp', '0002_rename_author_blog_branch_remove_blog_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='branch',
            new_name='author',
        ),
    ]
